#! /bin/bash

# script to make a release, suitable for github


pushd . > /dev/null
trap "popd > /dev/null" INT
echo "begin make-release"
cd ../.. 
version=$(grep -a -m 1 -h version pom.xml |cut -d '>' -f 2|cut -d '<' -f 1)

if [[ "$version" = "" ]]; then
	echo "ERROR: couldn't get version, exiting."
	popd > /dev/null
	exit 1
else
	echo "creating release version: $version"
fi

# basic assembly
packageDir="target/appassembler"
rm -rf "$packageDir"
mvn package -DskipTests=true
if [[ ! -e "$packageDir" ]]; then
	echo "ERROR: packing failed, exiting."
	popd > /dev/null
	exit 1
fi

# copy some extra files
cp Configuration.md "$packageDir"
cp README.md "$packageDir"
cp src/scripts/launch* "$packageDir"/bin

pushd "$packageDir" > /dev/null
zip -r "fv-$version".zip *
mv *.zip ../..
popd > /dev/null
ls -l *.zip

popd > /dev/null
echo "end make-release"
exit 0
